# Generated by Django 6.1.1 on 2026-09-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_diagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('issue_description', models.TextField()),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
